### ISSUE TITLE
ngx_http_api_module report "net.connectionsAcceptedPerSecond" with total request

### ISSUE THREAD

**Issue by AllanYin** [newrelic/nri-nginx#45]
I found out that the our Nginx newrelic integration dashboard is showing total request as request per second.

Please see below: 
<img width="952" alt="Screen Shot 2020-05-15 at 11 31 03 pm" src="https://user-images.githubusercontent.com/3792081/82056207-f4be5880-9704-11ea-9f69-cf5c8a653325.png">

I believe the problem is here:
https://github.com/newrelic/nri-nginx/blob/38246a6f8584a8077087ea749c7444586b3579b6/src/metrics.go#L33

For Nginx document, connections.accepted means total accepted request since start:
http://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_connections

Could we have a fix for this, please?

Cheers,
Allan

**Comment by ardias** [comment]
Hi @AllanYin . Thanks for bringing that up to our attention. We'll have a fix asap.

**Comment by luketn** [comment]
+1

**Comment by at0S** [comment]
+1

**Comment by luketn** [comment]
I've been putting together a dashboard of the Nginx statistics, and there are more stats also suffering the same issue reported here:
![image](https://user-images.githubusercontent.com/1756555/83595631-e8137e80-a5a5-11ea-996f-c7c18eafd814.png)

In this dashboard, we are using:
- 1xx, 2xx... responses
- requests per second
- connections accepted/dropped per second
- active connections

See the documentation for the API:
https://demo.nginx.com/swagger-ui/#/Method_GET/getHttpServerZones

They indicate that the statistics reported are 'total' values. I.e. they are the total value of each statistic.

The only graph on the dashboard which is correct, is the active connections graph. All the other graphs are incorrectly reporting data because of this 'total' issue.

As you can see the other graphs all go only up and never fall as the number of connections actually did fall.

**Comment by luketn** [comment]
I've been really struggling with making use of the nginx stats to make reliable dashboards in New Relic One.

Would it be possible to also provide some guidance on how to effectively build charts for these stats in NRQL to get accurate visualisations across a fleet of Nginx servers?

Turns out even the 'active connections' graph above was not quite accurate. To improve it I have been attempting to get it to work across our 6 instances reporting data through the agent. My most successful query is:
```
SELECT rate(sum(net.connectionsActive), 30 seconds) as 'Active Connections' FROM NginxSample TIMESERIES SINCE 1800 seconds ago
```

This query works well for a 30 minute time period (in the below there are 6 servers having a total of 8-9 connections):
![image](https://user-images.githubusercontent.com/1756555/83748381-74589b00-a6a5-11ea-824d-0cf555a00e2a.png)

However when you zoom in on it, the visualization goes to hell:
![image](https://user-images.githubusercontent.com/1756555/83748490-9f42ef00-a6a5-11ea-9588-e60daf2db7b2.png)
(I guess because the TIMESERIES window changed to < 30s?)

Likewise there are some inaccuracies over a longer time period (6 hours):
![image](https://user-images.githubusercontent.com/1756555/83748550-b97ccd00-a6a5-11ea-8647-f87c123d26e3.png)
In the above the peak shown is ~40k, however if you zoom into that 40k peak, this appears with a higher peak:
![image](https://user-images.githubusercontent.com/1756555/83748615-d1ece780-a6a5-11ea-84b2-382e83406a9b.png)

I'd really appreciate, alongside this fix to the reporting of stats in the New Relic agent for Nginx some guidance on how to consume the data and visualize it successfully. Thanks!

**Comment by ardias** [comment]
Hi @luketn ,
there is in fact issues with the Nginx Plus integration. We're currently working on fixing **global** metrics (metrics not associated with specific server zones, upstreams, etc) and at some later point we'll have a solution for those other metrics.

Sorry for the inconvenience.

**Comment by ardias** [comment]
Hi,
we have released a new version of the NGINx integration that fixes these issues: https://github.com/newrelic/nri-nginx/releases/tag/v3.0.0

It is available already in New Relic native package manage repositories.
